# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TableGraphView.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 455)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.horizontalTabWidget.setGeometry(QtCore.QRect(0, 0, 821, 441))
        self.horizontalTabWidget.setObjectName("horizontalTabWidget")
        self.horizontalTabWidgetPage1 = QtWidgets.QWidget()
        self.horizontalTabWidgetPage1.setObjectName("horizontalTabWidgetPage1")
        self.horizontalTabWidget.addTab(self.horizontalTabWidgetPage1, "")
        self.Vector2 = QtWidgets.QWidget()
        self.Vector2.setAccessibleName("")
        self.Vector2.setObjectName("Vector2")
        self.tableWidget = QtWidgets.QTableWidget(self.Vector2)
        self.tableWidget.setGeometry(QtCore.QRect(380, 40, 421, 251))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectColumns)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.pushButton = QtWidgets.QPushButton(self.Vector2)
        self.pushButton.setGeometry(QtCore.QRect(6, 0, 35, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 0, 35, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 0, 51, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(self.Vector2)
        self.comboBox.setGeometry(QtCore.QRect(80, 40, 53, 23))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.Vector2)
        self.label.setGeometry(QtCore.QRect(10, 40, 67, 23))
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 40, 56, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.Vector2)
        self.lineEdit.setGeometry(QtCore.QRect(445, 0, 115, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.Vector2)
        self.label_3.setGeometry(QtCore.QRect(380, 0, 62, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Vector2)
        self.label_4.setGeometry(QtCore.QRect(580, 0, 90, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Vector2)
        self.lineEdit_2.setGeometry(QtCore.QRect(670, 0, 115, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.Vector2)
        self.tableWidget_2.setGeometry(QtCore.QRect(380, 300, 271, 111))
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(4)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(2, 3, item)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.pushButton_6 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_6.setGeometry(QtCore.QRect(660, 300, 67, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_7.setGeometry(QtCore.QRect(730, 300, 67, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_8.setGeometry(QtCore.QRect(170, 0, 110, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_9.setGeometry(QtCore.QRect(660, 330, 100, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_10.setGeometry(QtCore.QRect(660, 360, 100, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.Vector2)
        self.pushButton_11.setGeometry(QtCore.QRect(280, 0, 85, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_2 = QtWidgets.QLabel(self.Vector2)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 35, 20))
        self.label_2.setObjectName("label_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.Vector2)
        self.checkBox_2.setGeometry(QtCore.QRect(430, 25, 21, 16))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.Vector2)
        self.checkBox_3.setGeometry(QtCore.QRect(510, 25, 21, 16))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.Vector2)
        self.checkBox_4.setGeometry(QtCore.QRect(620, 25, 21, 16))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.Vector2)
        self.checkBox_5.setGeometry(QtCore.QRect(720, 25, 21, 16))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.Vector2)
        self.checkBox_6.setGeometry(QtCore.QRect(780, 25, 21, 16))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.graphicsView = QtWidgets.QGraphicsView(self.Vector2)
        self.graphicsView.setGeometry(QtCore.QRect(10, 65, 361, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.label_5 = QtWidgets.QLabel(self.Vector2)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 47, 13))
        self.label_5.setObjectName("label_5")
        self.horizontalSlider = QtWidgets.QSlider(self.Vector2)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 75, 301, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalTabWidget.addTab(self.Vector2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalTabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalTabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.horizontalTabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.horizontalTabWidget.setTabText(self.horizontalTabWidget.indexOf(self.horizontalTabWidgetPage1), _translate("MainWindow", "Vector1"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "001"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "002"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "003"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "004"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Node ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Node Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Time of Occurrence"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Long Description"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Log Entry Reference"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Log Creator"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Event Type"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Icon Type"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Artifact"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Node Visibility"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "001"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "SQL Injection"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "7/18/2019 15:51"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Red Team succeded SQL Injection"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget.item(0, 5)
        item.setText(_translate("MainWindow", "White Team"))
        item = self.tableWidget.item(0, 6)
        item.setText(_translate("MainWindow", "Red Team"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "002"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "SQL Server"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "7/18/2019 16:30"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "Window SQL server"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget.item(1, 5)
        item.setText(_translate("MainWindow", "White Team"))
        item = self.tableWidget.item(1, 6)
        item.setText(_translate("MainWindow", "Blue Team"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "003"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "Window Log"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "7/18/2019 16:35"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "Windows log showing activity"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget.item(2, 5)
        item.setText(_translate("MainWindow", "White Team"))
        item = self.tableWidget.item(2, 6)
        item.setText(_translate("MainWindow", "Blue Team"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "004"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "Windo Log Con."))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "7/18/2019 16:40"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "Windows log SQL server"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "Link"))
        item = self.tableWidget.item(3, 5)
        item.setText(_translate("MainWindow", "BlueTeam"))
        item = self.tableWidget.item(3, 6)
        item.setText(_translate("MainWindow", "Blue Team"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Undo"))
        self.pushButton_2.setText(_translate("MainWindow", "Redo"))
        self.pushButton_4.setText(_translate("MainWindow", "Export"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Second"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Minute"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Hour"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Day"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Week"))
        self.label.setText(_translate("MainWindow", "Time Interval:"))
        self.pushButton_5.setText(_translate("MainWindow", "Flip Axis"))
        self.lineEdit.setText(_translate("MainWindow", "Vector2"))
        self.label_3.setText(_translate("MainWindow", "Vector Name"))
        self.label_4.setText(_translate("MainWindow", "Vector Description"))
        self.lineEdit_2.setText(_translate("MainWindow", "SQL Injection"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1-001"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1-002"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "1-003"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Relationship ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Parent"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Child"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Label"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        item = self.tableWidget_2.item(0, 0)
        item.setText(_translate("MainWindow", "2-001"))
        item = self.tableWidget_2.item(0, 1)
        item.setText(_translate("MainWindow", "001"))
        item = self.tableWidget_2.item(0, 2)
        item.setText(_translate("MainWindow", "002"))
        item = self.tableWidget_2.item(0, 3)
        item.setText(_translate("MainWindow", "Label X"))
        item = self.tableWidget_2.item(1, 0)
        item.setText(_translate("MainWindow", "2-002"))
        item = self.tableWidget_2.item(1, 1)
        item.setText(_translate("MainWindow", "002"))
        item = self.tableWidget_2.item(1, 2)
        item.setText(_translate("MainWindow", "003"))
        item = self.tableWidget_2.item(2, 0)
        item.setText(_translate("MainWindow", "2-003"))
        item = self.tableWidget_2.item(2, 1)
        item.setText(_translate("MainWindow", "003"))
        item = self.tableWidget_2.item(2, 2)
        item.setText(_translate("MainWindow", "004"))
        item = self.tableWidget_2.item(2, 3)
        item.setText(_translate("MainWindow", "Label Y"))
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.pushButton_6.setText(_translate("MainWindow", "Add Node"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete Node"))
        self.pushButton_8.setText(_translate("MainWindow", "Log Entry Navigation"))
        self.pushButton_9.setText(_translate("MainWindow", "Add Relationship"))
        self.pushButton_10.setText(_translate("MainWindow", "Delete Relationship"))
        self.pushButton_11.setText(_translate("MainWindow", "Version Control"))
        self.label_2.setText(_translate("MainWindow", "Visibility"))
        self.label_5.setText(_translate("MainWindow", "Time"))
        self.horizontalTabWidget.setTabText(self.horizontalTabWidget.indexOf(self.Vector2), _translate("MainWindow", "Vector2"))
        self.horizontalTabWidget.setTabText(self.horizontalTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Vector3"))
        self.horizontalTabWidget.setTabText(self.horizontalTabWidget.indexOf(self.tab), _translate("MainWindow", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
