# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_vectortableview.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow_vectortableview(object):

    def setupUi(self, mainwindow_vectortableview):
        mainwindow_vectortableview.setObjectName("mainwindow_vectortableview")
        mainwindow_vectortableview.resize(816, 576)
        self.centralwidget = QtWidgets.QWidget(mainwindow_vectortableview)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.vl_allwindow_gv = QtWidgets.QVBoxLayout()
        self.vl_allwindow_gv.setObjectName("vl_allwindow_gv")
        self.hl_top_gv = QtWidgets.QHBoxLayout()
        self.hl_top_gv.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hl_top_gv.setObjectName("hl_top_gv")
        self.button_undo_gv = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_undo_gv.sizePolicy().hasHeightForWidth())
        self.button_undo_gv.setSizePolicy(sizePolicy)
        self.button_undo_gv.setObjectName("button_undo_gv")
        self.hl_top_gv.addWidget(self.button_undo_gv)
        self.button_redo_gv = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_redo_gv.sizePolicy().hasHeightForWidth())
        self.button_redo_gv.setSizePolicy(sizePolicy)
        self.button_redo_gv.setObjectName("button_redo_gv")
        self.hl_top_gv.addWidget(self.button_redo_gv)
        self.button_push_gv = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_push_gv.sizePolicy().hasHeightForWidth())
        self.button_push_gv.setSizePolicy(sizePolicy)
        self.button_push_gv.setObjectName("button_push_gv")
        self.hl_top_gv.addWidget(self.button_push_gv)
        self.button_pull_gv = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pull_gv.sizePolicy().hasHeightForWidth())
        self.button_pull_gv.setSizePolicy(sizePolicy)
        self.button_pull_gv.setObjectName("button_pull_gv")
        self.hl_top_gv.addWidget(self.button_pull_gv)
        self.navigation_button_gv = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navigation_button_gv.sizePolicy().hasHeightForWidth())
        self.navigation_button_gv.setSizePolicy(sizePolicy)
        self.navigation_button_gv.setObjectName("navigation_button_gv")
        self.hl_top_gv.addWidget(self.navigation_button_gv)
        self.vl_allwindow_gv.addLayout(self.hl_top_gv)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vl_allwindow_gv.addItem(spacerItem)
        self.hl_vectoredit_gv = QtWidgets.QHBoxLayout()
        self.hl_vectoredit_gv.setObjectName("hl_vectoredit_gv")
        self.button_viewgraph_gv = QtWidgets.QPushButton(self.centralwidget)
        self.button_viewgraph_gv.setObjectName("button_viewgraph_gv")
        self.hl_vectoredit_gv.addWidget(self.button_viewgraph_gv)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hl_vectoredit_gv.addItem(spacerItem1)
        self.label_vectorname_gv = QtWidgets.QLabel(self.centralwidget)
        self.label_vectorname_gv.setObjectName("label_vectorname_gv")
        self.hl_vectoredit_gv.addWidget(self.label_vectorname_gv)
        self.lineedit_vectorname_gv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineedit_vectorname_gv.setObjectName("lineedit_vectorname_gv")
        self.hl_vectoredit_gv.addWidget(self.lineedit_vectorname_gv)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.hl_vectoredit_gv.addItem(spacerItem2)
        self.label_vectordescription_gv = QtWidgets.QLabel(self.centralwidget)
        self.label_vectordescription_gv.setObjectName("label_vectordescription_gv")
        self.hl_vectoredit_gv.addWidget(self.label_vectordescription_gv)
        self.linedit_vectordescription_gv = QtWidgets.QLineEdit(self.centralwidget)
        self.linedit_vectordescription_gv.setObjectName("linedit_vectordescription_gv")
        self.hl_vectoredit_gv.addWidget(self.linedit_vectordescription_gv)
        self.vl_allwindow_gv.addLayout(self.hl_vectoredit_gv)
        self.hl_nodevalues_gv = QtWidgets.QHBoxLayout()
        self.hl_nodevalues_gv.setObjectName("hl_nodevalues_gv")
        self.tablewidget_nodes_gv = QtWidgets.QTableWidget(self.centralwidget)
        self.tablewidget_nodes_gv.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tablewidget_nodes_gv.setObjectName("tablewidget_nodes_gv")
        self.tablewidget_nodes_gv.setColumnCount(10)
        self.tablewidget_nodes_gv.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_nodes_gv.setItem(3, 0, item)
        self.tablewidget_nodes_gv.horizontalHeader().setVisible(True)
        self.tablewidget_nodes_gv.horizontalHeader().setHighlightSections(True)
        self.tablewidget_nodes_gv.horizontalHeader().setStretchLastSection(True)
        self.tablewidget_nodes_gv.verticalHeader().setVisible(False)
        self.tablewidget_nodes_gv.verticalHeader().setHighlightSections(True)
        self.tablewidget_nodes_gv.verticalHeader().setStretchLastSection(True)
        self.hl_nodevalues_gv.addWidget(self.tablewidget_nodes_gv)
        self.vl_allwindow_gv.addLayout(self.hl_nodevalues_gv)
        self.hl_noderelationships_gv = QtWidgets.QHBoxLayout()
        self.hl_noderelationships_gv.setObjectName("hl_noderelationships_gv")
        self.vl_relationships_hl_noderelationships_gv = QtWidgets.QVBoxLayout()
        self.vl_relationships_hl_noderelationships_gv.setObjectName("vl_relationships_hl_noderelationships_gv")
        self.tablewidget_relationships_gv = QtWidgets.QTableWidget(self.centralwidget)
        self.tablewidget_relationships_gv.setMinimumSize(QtCore.QSize(425, 0))
        self.tablewidget_relationships_gv.setObjectName("tablewidget_relationships_gv")
        self.tablewidget_relationships_gv.setColumnCount(4)
        self.tablewidget_relationships_gv.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablewidget_relationships_gv.setHorizontalHeaderItem(3, item)
        self.tablewidget_relationships_gv.horizontalHeader().setStretchLastSection(True)
        self.tablewidget_relationships_gv.verticalHeader().setVisible(False)
        self.tablewidget_relationships_gv.verticalHeader().setStretchLastSection(True)
        self.vl_relationships_hl_noderelationships_gv.addWidget(self.tablewidget_relationships_gv)
        self.hl_noderelationships_gv.addLayout(self.vl_relationships_hl_noderelationships_gv)
        self.vl_modnoderelationship_hl_noderelationships_gv = QtWidgets.QVBoxLayout()
        self.vl_modnoderelationship_hl_noderelationships_gv.setObjectName("vl_modnoderelationship_hl_noderelationships_gv")
        self.hl_modnode_hl_noderelationships_gv = QtWidgets.QHBoxLayout()
        self.hl_modnode_hl_noderelationships_gv.setObjectName("hl_modnode_hl_noderelationships_gv")
        self.button_addnode_gv = QtWidgets.QPushButton(self.centralwidget)
        self.button_addnode_gv.setObjectName("button_addnode_gv")
        self.hl_modnode_hl_noderelationships_gv.addWidget(self.button_addnode_gv)
        self.button_deletenode_gv = QtWidgets.QPushButton(self.centralwidget)
        self.button_deletenode_gv.setObjectName("button_deletenode_gv")
        self.hl_modnode_hl_noderelationships_gv.addWidget(self.button_deletenode_gv)
        self.vl_modnoderelationship_hl_noderelationships_gv.addLayout(self.hl_modnode_hl_noderelationships_gv)
        self.hl_modrelationship_hl_noderelationships_gv = QtWidgets.QHBoxLayout()
        self.hl_modrelationship_hl_noderelationships_gv.setObjectName("hl_modrelationship_hl_noderelationships_gv")
        self.button_addrelationship_gv = QtWidgets.QPushButton(self.centralwidget)
        self.button_addrelationship_gv.setObjectName("button_addrelationship_gv")
        self.hl_modrelationship_hl_noderelationships_gv.addWidget(self.button_addrelationship_gv)
        self.button_deleterelationship_gv = QtWidgets.QPushButton(self.centralwidget)
        self.button_deleterelationship_gv.setObjectName("button_deleterelationship_gv")
        self.hl_modrelationship_hl_noderelationships_gv.addWidget(self.button_deleterelationship_gv)
        self.vl_modnoderelationship_hl_noderelationships_gv.addLayout(self.hl_modrelationship_hl_noderelationships_gv)
        self.hl_noderelationships_gv.addLayout(self.vl_modnoderelationship_hl_noderelationships_gv)
        self.vl_nodefilters_hl_noderelationships_gv = QtWidgets.QVBoxLayout()
        self.vl_nodefilters_hl_noderelationships_gv.setContentsMargins(0, -1, -1, -1)
        self.vl_nodefilters_hl_noderelationships_gv.setObjectName("vl_nodefilters_hl_noderelationships_gv")
        self.label_visibiltiytoggles_gv = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_visibiltiytoggles_gv.sizePolicy().hasHeightForWidth())
        self.label_visibiltiytoggles_gv.setSizePolicy(sizePolicy)
        self.label_visibiltiytoggles_gv.setObjectName("label_visibiltiytoggles_gv")
        self.vl_nodefilters_hl_noderelationships_gv.addWidget(self.label_visibiltiytoggles_gv)
        self.scrollarea_nodefilters_gv = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollarea_nodefilters_gv.sizePolicy().hasHeightForWidth())
        self.scrollarea_nodefilters_gv.setSizePolicy(sizePolicy)
        self.scrollarea_nodefilters_gv.setMinimumSize(QtCore.QSize(160, 0))
        self.scrollarea_nodefilters_gv.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollarea_nodefilters_gv.setWidgetResizable(True)
        self.scrollarea_nodefilters_gv.setObjectName("scrollarea_nodefilters_gv")
        self.scrollareawidgetcontents_nodefilters_gv = QtWidgets.QWidget()
        self.scrollareawidgetcontents_nodefilters_gv.setGeometry(QtCore.QRect(0, 0, 144, 302))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollareawidgetcontents_nodefilters_gv.sizePolicy().hasHeightForWidth())
        self.scrollareawidgetcontents_nodefilters_gv.setSizePolicy(sizePolicy)
        self.scrollareawidgetcontents_nodefilters_gv.setObjectName("scrollareawidgetcontents_nodefilters_gv")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollareawidgetcontents_nodefilters_gv)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkbox_nodevisibility_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_nodevisibility_gv.setObjectName("checkbox_nodevisibility_gv")
        self.gridLayout_2.addWidget(self.checkbox_nodevisibility_gv, 9, 0, 1, 1)
        self.checkbox_source_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_source_gv.setObjectName("checkbox_source_gv")
        self.gridLayout_2.addWidget(self.checkbox_source_gv, 8, 0, 1, 1)
        self.checkbox_eventtype_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_eventtype_gv.setObjectName("checkbox_eventtype_gv")
        self.gridLayout_2.addWidget(self.checkbox_eventtype_gv, 6, 0, 1, 1)
        self.checkbox_nodedescription_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_nodedescription_gv.setObjectName("checkbox_nodedescription_gv")
        self.gridLayout_2.addWidget(self.checkbox_nodedescription_gv, 3, 0, 1, 1)
        self.checkbox_logentryrefernce_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_logentryrefernce_gv.setObjectName("checkbox_logentryrefernce_gv")
        self.gridLayout_2.addWidget(self.checkbox_logentryrefernce_gv, 4, 0, 1, 1)
        self.checkbox_nodeid_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_nodeid_gv.sizePolicy().hasHeightForWidth())
        self.checkbox_nodeid_gv.setSizePolicy(sizePolicy)
        self.checkbox_nodeid_gv.setObjectName("checkbox_nodeid_gv")
        self.gridLayout_2.addWidget(self.checkbox_nodeid_gv, 0, 0, 1, 1)
        self.chekcbox_icontype_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.chekcbox_icontype_gv.setObjectName("chekcbox_icontype_gv")
        self.gridLayout_2.addWidget(self.chekcbox_icontype_gv, 7, 0, 1, 1)
        self.checkbox_nodename_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_nodename_gv.setObjectName("checkbox_nodename_gv")
        self.gridLayout_2.addWidget(self.checkbox_nodename_gv, 1, 0, 1, 1)
        self.checkbox_logcreator_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_logcreator_gv.setObjectName("checkbox_logcreator_gv")
        self.gridLayout_2.addWidget(self.checkbox_logcreator_gv, 5, 0, 1, 1)
        self.checkbox_nodetimestamp_gv = QtWidgets.QCheckBox(self.scrollareawidgetcontents_nodefilters_gv)
        self.checkbox_nodetimestamp_gv.setObjectName("checkbox_nodetimestamp_gv")
        self.gridLayout_2.addWidget(self.checkbox_nodetimestamp_gv, 2, 0, 1, 1)
        self.scrollarea_nodefilters_gv.setWidget(self.scrollareawidgetcontents_nodefilters_gv)
        self.vl_nodefilters_hl_noderelationships_gv.addWidget(self.scrollarea_nodefilters_gv)
        self.hl_noderelationships_gv.addLayout(self.vl_nodefilters_hl_noderelationships_gv)
        self.vl_allwindow_gv.addLayout(self.hl_noderelationships_gv)
        self.gridLayout.addLayout(self.vl_allwindow_gv, 0, 0, 1, 1)
        mainwindow_vectortableview.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainwindow_vectortableview)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 816, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menuVectors = QtWidgets.QMenu(self.menubar)
        self.menuVectors.setObjectName("menuVectors")
        mainwindow_vectortableview.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainwindow_vectortableview)
        self.statusbar.setObjectName("statusbar")
        mainwindow_vectortableview.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuVectors.menuAction())

        self.retranslateUi(mainwindow_vectortableview)
        QtCore.QMetaObject.connectSlotsByName(mainwindow_vectortableview)
        self.button_setup()

    def button_setup(self):
        self.button_undo_gv.setCheckable(True)
        self.button_undo_gv.clicked.connect(self.button_undo_gv_clicked)
        self.button_redo_gv.setCheckable(True)
        self.button_redo_gv.clicked.connect(self.button_redo_gv_clicked)

        self.button_push_gv.setCheckable(True)
        self.button_push_gv.clicked.connect(self.button_push_gv_clicked)
        self.button_pull_gv.setCheckable(True)
        self.button_pull_gv.clicked.connect(self.button_pull_gv_clicked)

        self.navigation_button_gv.setCheckable(True)
        self.navigation_button_gv.clicked.connect(self.navigation_button_gv_clicked)

        self.button_viewgraph_gv.setCheckable(True)
        self.button_viewgraph_gv.clicked.connect(self.button_viewgraph_gv_clicked)

        self.button_addnode_gv.setCheckable(True)
        self.button_addnode_gv.clicked.connect(self.button_addnode_gv_clicked)
        self.button_deletenode_gv.setCheckable(True)
        self.button_deletenode_gv.clicked.connect(self.button_deletenode_gv_clicked)

        self.button_addrelationship_gv.setCheckable(True)
        self.button_addrelationship_gv.clicked.connect(self.button_addrelationship_gv_clicked)
        self.button_deleterelationship_gv.setCheckable(True)
        self.button_deleterelationship_gv.clicked.connect(self.button_deleterelationship_gv_clicked)

    def retranslateUi(self, mainwindow_vectortableview):
        _translate = QtCore.QCoreApplication.translate
        mainwindow_vectortableview.setWindowTitle(_translate("mainwindow_vectortableview", "Vector Table View"))
        self.button_undo_gv.setText(_translate("mainwindow_vectortableview", "Undo"))
        self.button_redo_gv.setText(_translate("mainwindow_vectortableview", "Redo"))
        self.button_push_gv.setText(_translate("mainwindow_vectortableview", "Push"))
        self.button_pull_gv.setText(_translate("mainwindow_vectortableview", "Pull"))
        self.navigation_button_gv.setText(_translate("mainwindow_vectortableview", "Navigation"))
        self.button_viewgraph_gv.setText(_translate("mainwindow_vectortableview", "View Graph"))
        self.label_vectorname_gv.setText(_translate("mainwindow_vectortableview", "Vector Name"))
        self.lineedit_vectorname_gv.setText(_translate("mainwindow_vectortableview", "Vector02"))
        self.label_vectordescription_gv.setText(_translate("mainwindow_vectortableview", "Vector Description"))
        self.linedit_vectordescription_gv.setText(_translate("mainwindow_vectortableview", "SQL Injection"))
        item = self.tablewidget_nodes_gv.verticalHeaderItem(0)
        item.setText(_translate("mainwindow_vectortableview", "Node 01"))
        item = self.tablewidget_nodes_gv.verticalHeaderItem(1)
        item.setText(_translate("mainwindow_vectortableview", "Node 02"))
        item = self.tablewidget_nodes_gv.verticalHeaderItem(2)
        item.setText(_translate("mainwindow_vectortableview", "Node 03"))
        item = self.tablewidget_nodes_gv.verticalHeaderItem(3)
        item.setText(_translate("mainwindow_vectortableview", "Node 04"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow_vectortableview", "Node ID"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow_vectortableview", "Node Name"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow_vectortableview", "Node Timestamp"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow_vectortableview", "Node Description"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(4)
        item.setText(_translate("mainwindow_vectortableview", "Log Entry Reference"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(5)
        item.setText(_translate("mainwindow_vectortableview", "Log Creator"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(6)
        item.setText(_translate("mainwindow_vectortableview", "Event Type"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(7)
        item.setText(_translate("mainwindow_vectortableview", "Icon Type"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(8)
        item.setText(_translate("mainwindow_vectortableview", "Source"))
        item = self.tablewidget_nodes_gv.horizontalHeaderItem(9)
        item.setText(_translate("mainwindow_vectortableview", "Node Visibiltiy"))
        __sortingEnabled = self.tablewidget_nodes_gv.isSortingEnabled()
        self.tablewidget_nodes_gv.setSortingEnabled(False)
        item = self.tablewidget_nodes_gv.item(0, 0)
        item.setText(_translate("mainwindow_vectortableview", "001"))
        item = self.tablewidget_nodes_gv.item(1, 0)
        item.setText(_translate("mainwindow_vectortableview", "002"))
        item = self.tablewidget_nodes_gv.item(2, 0)
        item.setText(_translate("mainwindow_vectortableview", "003"))
        item = self.tablewidget_nodes_gv.item(3, 0)
        item.setText(_translate("mainwindow_vectortableview", "004"))
        self.tablewidget_nodes_gv.setSortingEnabled(__sortingEnabled)
        item = self.tablewidget_relationships_gv.verticalHeaderItem(0)
        item.setText(_translate("mainwindow_vectortableview", "01"))
        item = self.tablewidget_relationships_gv.verticalHeaderItem(1)
        item.setText(_translate("mainwindow_vectortableview", "02"))
        item = self.tablewidget_relationships_gv.verticalHeaderItem(2)
        item.setText(_translate("mainwindow_vectortableview", "03"))
        item = self.tablewidget_relationships_gv.verticalHeaderItem(3)
        item.setText(_translate("mainwindow_vectortableview", "04"))
        item = self.tablewidget_relationships_gv.horizontalHeaderItem(0)
        item.setText(_translate("mainwindow_vectortableview", "Relationship ID"))
        item = self.tablewidget_relationships_gv.horizontalHeaderItem(1)
        item.setText(_translate("mainwindow_vectortableview", "Parent"))
        item = self.tablewidget_relationships_gv.horizontalHeaderItem(2)
        item.setText(_translate("mainwindow_vectortableview", "Child"))
        item = self.tablewidget_relationships_gv.horizontalHeaderItem(3)
        item.setText(_translate("mainwindow_vectortableview", "Label"))
        self.button_addnode_gv.setText(_translate("mainwindow_vectortableview", "Add Node"))
        self.button_deletenode_gv.setText(_translate("mainwindow_vectortableview", "Delete Node"))
        self.button_addrelationship_gv.setText(_translate("mainwindow_vectortableview", "Add Relationship"))
        self.button_deleterelationship_gv.setText(_translate("mainwindow_vectortableview", "Delete Relationship"))
        self.label_visibiltiytoggles_gv.setText(_translate("mainwindow_vectortableview", "Visibility Toggles"))
        self.checkbox_nodevisibility_gv.setText(_translate("mainwindow_vectortableview", "Node Visibility"))
        self.checkbox_source_gv.setText(_translate("mainwindow_vectortableview", "Source"))
        self.checkbox_eventtype_gv.setText(_translate("mainwindow_vectortableview", "Event Type"))
        self.checkbox_nodedescription_gv.setText(_translate("mainwindow_vectortableview", "Node Description"))
        self.checkbox_logentryrefernce_gv.setText(_translate("mainwindow_vectortableview", "Log Entry Reference"))
        self.checkbox_nodeid_gv.setText(_translate("mainwindow_vectortableview", "Node ID"))
        self.chekcbox_icontype_gv.setText(_translate("mainwindow_vectortableview", "Icon Type"))
        self.checkbox_nodename_gv.setText(_translate("mainwindow_vectortableview", "Node Name"))
        self.checkbox_logcreator_gv.setText(_translate("mainwindow_vectortableview", "Log Creator"))
        self.checkbox_nodetimestamp_gv.setText(_translate("mainwindow_vectortableview", "Node Timestamp"))
        self.menuVectors.setTitle(_translate("mainwindow_vectortableview", "Vectors"))

    def button_undo_gv_clicked(self):
        print(self.button_undo_gv.text())
        self.button_undo_gv.toggle()

    def button_redo_gv_clicked(self):
        print(self.button_redo_gv.text())
        self.button_redo_gv.toggle()

    def button_push_gv_clicked(self):
        print(self.button_push_gv.text())
        self.button_push_gv.toggle()

    def button_pull_gv_clicked(self):
        print(self.button_pull_gv.text())
        self.button_pull_gv.toggle()

    def navigation_button_gv_clicked(self):
        from mainwindow_nav import Ui_mainwindow_navigation
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_mainwindow_navigation()
        self.ui.setupUi(self.window)
        mainwindow_vectortableview.hide()
        self.window.show()

    def button_viewgraph_gv_clicked(self):
        print(self.button_viewgraph_gv.text())
        self.button_viewgraph_gv.toggle()

    def button_addnode_gv_clicked(self):
        print(self.button_addnode_gv.text())
        self.button_addnode_gv.toggle()

    def button_deletenode_gv_clicked(self):
        print(self.button_deletenode_gv.text())
        self.button_deletenode_gv.toggle()

    def button_addrelationship_gv_clicked(self):
        print(self.button_addrelationship_gv.text())
        self.button_addrelationship_gv.toggle()

    def button_deleterelationship_gv_clicked(self):
        print(self.button_deleterelationship_gv.text())
        self.button_deleterelationship_gv.toggle()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainwindow_vectortableview = QtWidgets.QMainWindow()
    ui = Ui_mainwindow_vectortableview()
    ui.setupUi(mainwindow_vectortableview)
    mainwindow_vectortableview.show()
    sys.exit(app.exec_())